<?php
// this file is autogenerated by deploy script

return array (
  'default' => 
  array (
    'allowWebInterfaceOnDomains' => 'scalia-wptheme.loc',
    'rootDir' => '',
    'sync' => 
    array (
      'default' => 
      array (
        'defaultTasks' => 
        array (
          0 => 'default',
        ),
        'ignoreFiles' => '/deploy_config.php|/\\.git|.*/\\.(gitignore|svn)|/\\.(idea|settings|buildpath|project)|/\\.grunt|/node_modules|/package.json|/Gruntfile.js|.*/(Thumbs\\.db|\\.DS_Store)|.*~|/deploy_backups|/css/custom.css',
        'doBackup' => true,
        'backupDir' => 'deploy_backups/',
      ),
    ),
    'apiKey' => 'fd5d25bb268b76e61b9895ee2634c1fc53c7f3ac',
  ),
);